
CREATE TABLE public.cliente (
  id_cliente integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nome character varying NOT NULL,
  codigo_cliente character varying NOT NULL UNIQUE,
  ativo boolean NOT NULL DEFAULT true,
  data_cadastro timestamp with time zone NOT NULL DEFAULT now()
);

ALTER TABLE public.cliente ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Authenticated users can view clientes"
  ON public.cliente FOR SELECT
  TO authenticated
  USING (true);

CREATE POLICY "Admins can insert clientes"
  ON public.cliente FOR INSERT
  TO authenticated
  WITH CHECK (public.is_current_user_admin());

CREATE POLICY "Admins can update clientes"
  ON public.cliente FOR UPDATE
  TO authenticated
  USING (public.is_current_user_admin());

CREATE POLICY "Admins can delete clientes"
  ON public.cliente FOR DELETE
  TO authenticated
  USING (public.is_current_user_admin());
